[[redirects]]
  from = "http://braverybooks.com/*"
  to = "https://erinhayden.com/bravery-books"
  status = 301
  force = true

[[redirects]]
  from = "https://braverybooks.com/*"
  to = "https://erinhayden.com/bravery-books"
  status = 301
  force = true

[[redirects]]
  from = "http://www.braverybooks.com/*"
  to = "https://erinhayden.com/bravery-books"
  status = 301
  force = true

[[redirects]]
  from = "https://www.braverybooks.com/*"
  to = "https://erinhayden.com/bravery-books"
  status = 301
  force = true
